from __future__ import annotations

import base64
from pathlib import Path
from urllib.parse import quote

from vsf_profiler.ingestion.csv_catalog import CsvCatalog
from vsf_profiler.models import ColumnSchema, Schema, TableSchema


MAX_DBML_LINK_CHARS = 16_000


def build_schema_diagram(schema: Schema, catalog: CsvCatalog, out_dir: Path) -> dict:
    dbml = render_dbml_for_diagram(schema, catalog)
    dbml_path = out_dir / "schema_diagram.dbml"
    dbml_path.write_text(dbml)

    encoded = quote(base64.b64encode(dbml.encode("utf-8")).decode("ascii"), safe="")
    dbdiagram_url = f"https://dbdiagram.io/embed?c={encoded}"
    if len(dbdiagram_url) > MAX_DBML_LINK_CHARS:
        dbdiagram_url = ""

    diagram = {
        "dbml_path": dbml_path.name,
        "dbdiagram_url": dbdiagram_url,
        "dbdiagram_url_available": bool(dbdiagram_url),
        "dbdiagram_note": (
            "Open this stateless dbdiagram.io link to view the DBML ER diagram."
            if dbdiagram_url
            else "DBML is too large for a safe dbdiagram.io URL; use schema_diagram.dbml instead."
        ),
        "tables": [_table_mapping(table_name, table_schema, catalog) for table_name, table_schema in schema.tables.items()],
        "relationships": [rel.model_dump() for rel in schema.relationships],
        "extra_csvs": [
            {"table": stem, "csv_path": f"{stem}.csv", "status": "extra_csv"}
            for stem in catalog.extra_csvs
        ],
        "mermaid": render_mermaid_for_diagram(schema),
    }
    return diagram

import re

def render_mermaid_for_diagram(schema: Schema) -> str:
    blocks = ["erDiagram"]
    for table_name, table_schema in schema.tables.items():
        safe_table_name = re.sub(r'[^a-zA-Z0-9_]', '_', table_name)
        blocks.append(f"  {safe_table_name} {{")
        for column in table_schema.columns.values():
            key_marker = ""
            if column.is_pk and column.foreign_key:
                key_marker = " PK,FK"
            elif column.is_pk:
                key_marker = " PK"
            elif column.foreign_key:
                key_marker = " FK"
            
            # Escape type strings for mermaid
            col_type = re.sub(r'[^a-zA-Z0-9_]', '_', column.type)
            safe_col_name = re.sub(r'[^a-zA-Z0-9_]', '_', column.name)
            blocks.append(f"    {col_type} {safe_col_name}{key_marker}")
        blocks.append("  }")
        
    for rel in schema.relationships:
        # Default to one-to-many relationship as a safe approximation
        safe_parent = re.sub(r'[^a-zA-Z0-9_]', '_', rel.parent_table)
        safe_child = re.sub(r'[^a-zA-Z0-9_]', '_', rel.child_table)
        blocks.append(f'  {safe_parent} ||--o{{ {safe_child} : "{rel.parent_column} -> {rel.child_column}"')
        
    return "\n".join(blocks)



def render_dbml_for_diagram(schema: Schema, catalog: CsvCatalog) -> str:
    blocks: list[str] = [
        "// Generated by VSF Data Profiler.",
        "// The CSV mapping is also written to schema_diagram.json and the report.",
        "",
    ]
    for table_name, table_schema in schema.tables.items():
        catalog_table = catalog.tables.get(table_name)
        csv_note = f"CSV: {_source_label(catalog_table)}" if catalog_table else "CSV: missing"
        blocks.append(f"Table {table_name} {{")
        blocks.append(f"  Note: '{_escape_dbml_note(csv_note)}'")
        for column in table_schema.columns.values():
            blocks.append(f"  {_render_column(column)}")
        if len(table_schema.primary_key) > 1:
            pk = ", ".join(table_schema.primary_key)
            blocks.extend(["", "  indexes {", f"    ({pk}) [pk]", "  }"])
        blocks.append("}")
        blocks.append("")
    return "\n".join(blocks).rstrip() + "\n"


def _render_column(column: ColumnSchema) -> str:
    attrs: list[str] = []
    if column.is_pk:
        attrs.append("pk")
    if column.not_null:
        attrs.append("not null")
    if column.unique:
        attrs.append("unique")
    if column.foreign_key:
        attrs.append(f"ref: > {column.foreign_key.parent_table}.{column.foreign_key.parent_column}")
    suffix = f" [{', '.join(attrs)}]" if attrs else ""
    return f"{column.name} {column.type}{suffix}"


def _table_mapping(table_name: str, table_schema: TableSchema, catalog: CsvCatalog) -> dict:
    catalog_table = catalog.tables.get(table_name)
    mapping = _mapping_evidence(table_name, catalog, catalog_table)
    relationships = []
    for column in table_schema.columns.values():
        if column.foreign_key:
            relationships.append(
                {
                    "column": column.name,
                    "parent_table": column.foreign_key.parent_table,
                    "parent_column": column.foreign_key.parent_column,
                }
            )
    return {
        "table": table_name,
        "csv_path": _source_label(catalog_table) if catalog_table else "",
        "status": mapping["mapping_method"] if catalog_table else mapping["status"],
        "mapping_method": mapping["mapping_method"],
        "confidence": mapping["confidence"],
        "selected_csv": mapping["selected_csv"],
        "matched_columns": mapping["matched_columns"],
        "missing_columns": mapping["missing_columns"],
        "extra_columns": mapping["extra_columns"],
        "candidates": mapping["candidates"],
        "primary_key": table_schema.primary_key,
        "foreign_keys": relationships,
        "column_count": len(table_schema.columns),
    }


def _escape_dbml_note(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def _source_label(catalog_table) -> str:
    if catalog_table is None:
        return ""
    return catalog_table.source_name or str(catalog_table.csv_path)


def _mapping_evidence(table_name: str, catalog: CsvCatalog, catalog_table) -> dict:
    evidence = catalog.mapping_evidence.get(table_name)
    if evidence is not None:
        return evidence.model_dump(mode="json")
    if catalog_table is not None:
        return {
            "mapping_method": catalog_table.mapping_method,
            "status": "mapped",
            "confidence": catalog_table.mapping_confidence,
            "selected_csv": _source_label(catalog_table),
            "matched_columns": [],
            "missing_columns": [],
            "extra_columns": [],
            "candidates": [],
        }
    return {
        "mapping_method": "unmapped",
        "status": "missing_csv",
        "confidence": 0.0,
        "selected_csv": None,
        "matched_columns": [],
        "missing_columns": [],
        "extra_columns": [],
        "candidates": [],
    }
